WebApplication1/Models/AuctionViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication1.Models
{
    public class AuctionViewModel
    {
        List<ItemViewModel> Items { get; set; }
        List<String> Categories { get; set; }
    }
}

WebApplication1/Models/BidViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication1.Models
{
    public class BidFormViewModel
    {
        public ItemViewModel Item {get;set;}

        [Required]
        [StringLength(100)]
        public string Firstname{ get; set; }

        [Required]
        [StringLength(100)]
        public string Lastname{ get; set; }

        [Required]
        [Range(0.0, Double.MaxValue)]
        public double Amount { get; set; }
    }
}

WebApplication1/Models/ErrorViewModel.cs
using System;

namespace WebApplication1.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebApplication1/Models/ItemViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication1.Models
{
    public class ItemViewModel
    {
        public String ProductId { get; set; }
        public String ProductName { get; set; }
        public String ProductDescription { get; set; }
        public String BiddingEndDate { get; set; }
        public String ProductCategory { get; set; }
    }
}

WebApplication1/Controllers/BidController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WebApplication1.DAL.Model;
using WebApplication1.Models;
using WebApplication1.Services;
using WebApplication1.Services.Interfaces;

namespace WebApplication1.Controllers
{
    public class BidController : Controller
    {
        private IBidService bidService;

        public BidController(IBidService bidService)
        {
            this.bidService = bidService;
        }

        public IActionResult BidForm(ItemViewModel item)
        {
            var x = new BidFormViewModel { Item = item };
            return View(x);
        }

        public IActionResult AddBid(BidFormViewModel bid)
        {
            if (ModelState.IsValid)
            {
                bidService.Add(bid);
                return RedirectToAction("Index", "Item");
            }
            return View("BidForm", bid);
           
        }

        public IActionResult GetBid()
        {
            return View(bidService.GetBid());
        }
    }
}

WebApplication1/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebApplication1/Controllers/ItemController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WebApplication1.Models;
using WebApplication1.Services;
using WebApplication1.Services.Interfaces;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace WebApplication1.Controllers
{
    public class ItemController : Controller
    {
        IItemService itemService;

        public ItemController(IItemService itemService)
        {
            this.itemService = itemService;
        }


        public IActionResult Index(string category)
        {
            ViewBag.Categories = itemService.GetItemCategories();
            List<ItemViewModel> items = itemService.GetItems();

            if (category == null)
            {
                return View(items);
            }
            
            return View(itemService.GetItemsByCategory(category, items));
        }

        

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebApplication1/Views/Bid/BidForm.cshtml
@model WebApplication1.Models.BidFormViewModel
@{
    ViewData["Title"] = "BidForm";
}

<hr />
<div>
    <h2>Bid</h2>
    <p><b>Product Name:</b> @Html.DisplayFor(model => model.Item.ProductName)</p>
    
    @*<table class="table">
        <thead>
            <tr>
                <th>
                    Product Name
                </th>
                <th>
                    Product Descriptioin
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>
                    @Html.DisplayFor(model => model.Item.ProductName)
                </td>
                <td>
                    @Html.DisplayFor(model => model.Item.ProductDescription)
                </td>
            </tr>
        </tbody>
    </table>*@
</div>
@using (Html.BeginForm("AddBid", "Bid"))
{
<div class="form-horizontal">
    @Html.ValidationSummary(true)
    @Html.HiddenFor(model => model.Item.ProductId)
    @Html.HiddenFor(model => model.Item.BiddingEndDate)
    @Html.HiddenFor(model => model.Item.ProductName)
    @Html.HiddenFor(model => model.Item.ProductDescription)
    <div class="form-group">
        @Html.LabelFor(model => model.Firstname, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Firstname)
            @Html.ValidationMessageFor(model => model.Firstname)
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Lastname, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Lastname)
            @Html.ValidationMessageFor(model => model.Lastname)
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Amount, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Amount)
            @Html.ValidationMessageFor(model => model.Amount)
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Submit" class="btn btn-default" />
        </div>
    </div>
</div>
}

WebApplication1/Views/Bid/GetBid.cshtml
@model IEnumerable<WebApplication1.DAL.Model.Bid>

@{
    ViewData["Title"] = "GetBid";
}

<table class="table">
    <thead>
        <tr>
                <th>
                    @Html.DisplayNameFor(model => model.BidId)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Firstname)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Lastname)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Amount)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ItemId)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Time)
                </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.BidId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Firstname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Lastname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Amount)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ItemId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Time)
            </td>
            <td>
        </tr>
}
    </tbody>
</table>

WebApplication1/Views/Item/Index.cshtml
@model IEnumerable<WebApplication1.Models.ItemViewModel>

@Html.Partial("Menu")

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ProductName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ProductDescription)
            </th>
            <th>
                Expires in
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.ProductName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ProductDescription)
                </td>
                <td class="countdown">
                    @Html.DisplayFor(modelItem => item.BiddingEndDate)
                </td>
                <td class="bidButton">
                    @Html.ActionLink("Bid", "BidForm", "Bid", item)
                </td>
            </tr>
        }
    </tbody>
</table>

<script>
    // Set the date we're counting down to
    var elements = document.getElementsByClassName("countdown");
    var countDownDate = [];

    for (var i = 0; i < elements.length; i++) {
        countDownDate.push(new Date(elements[i].textContent).getTime());
    }

    console.log(countDownDate);
        //new Date(document.getElementsByClassName("countdown").textContent)
    //    new Date("Aug 17, 2018 13:16:25").getTime();
  // console.log(countDownDate.toString());
    // Update the count down every 1 second
    var x = setInterval(function () {

       
        var now = new Date().getTime();

        for (var i = 0; i < countDownDate.length; i++) {

            var distance = countDownDate[i] - now;
            // Time calculations for days, hours, minutes and seconds
            var days = Math.floor(distance / (1000 * 60 * 60 * 24));
            var hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
            var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
            var seconds = Math.floor((distance % (1000 * 60)) / 1000);
            // Output the result in an element with id="demo"
            document.getElementsByClassName("countdown")[i].innerHTML = days + "d " + hours + "h "
                + minutes + "m " + seconds + "s ";

            // If the count down is over, write some text
            if (distance < 0) {
                document.getElementsByClassName("countdown")[i].innerHTML = "EXPIRED";
                location.reload();
                document.getElementsByClassName("bidButton")[i].style.display = "none";
            }
        }
    }, 1000);
</script>

WebApplication1/Views/Shared/Menu.cshtml
<hr />
<div class="dropdown">
    <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">
        Categories
        <span class="caret"></span>
    </button>
    <ul class="dropdown-menu">
        @foreach (string category in ViewBag.Categories)
        {
            <li><a href="@Url.Action("Index", "Item", new { category = category })"> @category</a></li>
        }
        <li><a href="@Url.Action("Index", "Item")"> Reset</a></li>
    </ul>
</div>

WebApplication1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication1</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Item" asp-action="Index" class="navbar-brand">Online auction</a>
            </div>
           
               
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Item" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Bid" asp-action="GetBid">Bid History</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            @*<p>&copy; 2018 - WebApplication1</p>*@
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>